// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/RTradeLtd/grpc/krab"
	"google.golang.org/grpc"
)

type FakeServiceClient struct {
	DeletePrivateKeyStub        func(context.Context, *krab.KeyDelete, ...grpc.CallOption) (*krab.Response, error)
	deletePrivateKeyMutex       sync.RWMutex
	deletePrivateKeyArgsForCall []struct {
		arg1 context.Context
		arg2 *krab.KeyDelete
		arg3 []grpc.CallOption
	}
	deletePrivateKeyReturns struct {
		result1 *krab.Response
		result2 error
	}
	deletePrivateKeyReturnsOnCall map[int]struct {
		result1 *krab.Response
		result2 error
	}
	GetPrivateKeyStub        func(context.Context, *krab.KeyGet, ...grpc.CallOption) (*krab.Response, error)
	getPrivateKeyMutex       sync.RWMutex
	getPrivateKeyArgsForCall []struct {
		arg1 context.Context
		arg2 *krab.KeyGet
		arg3 []grpc.CallOption
	}
	getPrivateKeyReturns struct {
		result1 *krab.Response
		result2 error
	}
	getPrivateKeyReturnsOnCall map[int]struct {
		result1 *krab.Response
		result2 error
	}
	HasPrivateKeyStub        func(context.Context, *krab.KeyGet, ...grpc.CallOption) (*krab.Response, error)
	hasPrivateKeyMutex       sync.RWMutex
	hasPrivateKeyArgsForCall []struct {
		arg1 context.Context
		arg2 *krab.KeyGet
		arg3 []grpc.CallOption
	}
	hasPrivateKeyReturns struct {
		result1 *krab.Response
		result2 error
	}
	hasPrivateKeyReturnsOnCall map[int]struct {
		result1 *krab.Response
		result2 error
	}
	ListPrivateKeysStub        func(context.Context, *krab.KeyList, ...grpc.CallOption) (*krab.Response, error)
	listPrivateKeysMutex       sync.RWMutex
	listPrivateKeysArgsForCall []struct {
		arg1 context.Context
		arg2 *krab.KeyList
		arg3 []grpc.CallOption
	}
	listPrivateKeysReturns struct {
		result1 *krab.Response
		result2 error
	}
	listPrivateKeysReturnsOnCall map[int]struct {
		result1 *krab.Response
		result2 error
	}
	PutPrivateKeyStub        func(context.Context, *krab.KeyPut, ...grpc.CallOption) (*krab.Response, error)
	putPrivateKeyMutex       sync.RWMutex
	putPrivateKeyArgsForCall []struct {
		arg1 context.Context
		arg2 *krab.KeyPut
		arg3 []grpc.CallOption
	}
	putPrivateKeyReturns struct {
		result1 *krab.Response
		result2 error
	}
	putPrivateKeyReturnsOnCall map[int]struct {
		result1 *krab.Response
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceClient) DeletePrivateKey(arg1 context.Context, arg2 *krab.KeyDelete, arg3 ...grpc.CallOption) (*krab.Response, error) {
	fake.deletePrivateKeyMutex.Lock()
	ret, specificReturn := fake.deletePrivateKeyReturnsOnCall[len(fake.deletePrivateKeyArgsForCall)]
	fake.deletePrivateKeyArgsForCall = append(fake.deletePrivateKeyArgsForCall, struct {
		arg1 context.Context
		arg2 *krab.KeyDelete
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	fake.recordInvocation("DeletePrivateKey", []interface{}{arg1, arg2, arg3})
	fake.deletePrivateKeyMutex.Unlock()
	if fake.DeletePrivateKeyStub != nil {
		return fake.DeletePrivateKeyStub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.deletePrivateKeyReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceClient) DeletePrivateKeyCallCount() int {
	fake.deletePrivateKeyMutex.RLock()
	defer fake.deletePrivateKeyMutex.RUnlock()
	return len(fake.deletePrivateKeyArgsForCall)
}

func (fake *FakeServiceClient) DeletePrivateKeyCalls(stub func(context.Context, *krab.KeyDelete, ...grpc.CallOption) (*krab.Response, error)) {
	fake.deletePrivateKeyMutex.Lock()
	defer fake.deletePrivateKeyMutex.Unlock()
	fake.DeletePrivateKeyStub = stub
}

func (fake *FakeServiceClient) DeletePrivateKeyArgsForCall(i int) (context.Context, *krab.KeyDelete, []grpc.CallOption) {
	fake.deletePrivateKeyMutex.RLock()
	defer fake.deletePrivateKeyMutex.RUnlock()
	argsForCall := fake.deletePrivateKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeServiceClient) DeletePrivateKeyReturns(result1 *krab.Response, result2 error) {
	fake.deletePrivateKeyMutex.Lock()
	defer fake.deletePrivateKeyMutex.Unlock()
	fake.DeletePrivateKeyStub = nil
	fake.deletePrivateKeyReturns = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) DeletePrivateKeyReturnsOnCall(i int, result1 *krab.Response, result2 error) {
	fake.deletePrivateKeyMutex.Lock()
	defer fake.deletePrivateKeyMutex.Unlock()
	fake.DeletePrivateKeyStub = nil
	if fake.deletePrivateKeyReturnsOnCall == nil {
		fake.deletePrivateKeyReturnsOnCall = make(map[int]struct {
			result1 *krab.Response
			result2 error
		})
	}
	fake.deletePrivateKeyReturnsOnCall[i] = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) GetPrivateKey(arg1 context.Context, arg2 *krab.KeyGet, arg3 ...grpc.CallOption) (*krab.Response, error) {
	fake.getPrivateKeyMutex.Lock()
	ret, specificReturn := fake.getPrivateKeyReturnsOnCall[len(fake.getPrivateKeyArgsForCall)]
	fake.getPrivateKeyArgsForCall = append(fake.getPrivateKeyArgsForCall, struct {
		arg1 context.Context
		arg2 *krab.KeyGet
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	fake.recordInvocation("GetPrivateKey", []interface{}{arg1, arg2, arg3})
	fake.getPrivateKeyMutex.Unlock()
	if fake.GetPrivateKeyStub != nil {
		return fake.GetPrivateKeyStub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getPrivateKeyReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceClient) GetPrivateKeyCallCount() int {
	fake.getPrivateKeyMutex.RLock()
	defer fake.getPrivateKeyMutex.RUnlock()
	return len(fake.getPrivateKeyArgsForCall)
}

func (fake *FakeServiceClient) GetPrivateKeyCalls(stub func(context.Context, *krab.KeyGet, ...grpc.CallOption) (*krab.Response, error)) {
	fake.getPrivateKeyMutex.Lock()
	defer fake.getPrivateKeyMutex.Unlock()
	fake.GetPrivateKeyStub = stub
}

func (fake *FakeServiceClient) GetPrivateKeyArgsForCall(i int) (context.Context, *krab.KeyGet, []grpc.CallOption) {
	fake.getPrivateKeyMutex.RLock()
	defer fake.getPrivateKeyMutex.RUnlock()
	argsForCall := fake.getPrivateKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeServiceClient) GetPrivateKeyReturns(result1 *krab.Response, result2 error) {
	fake.getPrivateKeyMutex.Lock()
	defer fake.getPrivateKeyMutex.Unlock()
	fake.GetPrivateKeyStub = nil
	fake.getPrivateKeyReturns = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) GetPrivateKeyReturnsOnCall(i int, result1 *krab.Response, result2 error) {
	fake.getPrivateKeyMutex.Lock()
	defer fake.getPrivateKeyMutex.Unlock()
	fake.GetPrivateKeyStub = nil
	if fake.getPrivateKeyReturnsOnCall == nil {
		fake.getPrivateKeyReturnsOnCall = make(map[int]struct {
			result1 *krab.Response
			result2 error
		})
	}
	fake.getPrivateKeyReturnsOnCall[i] = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) HasPrivateKey(arg1 context.Context, arg2 *krab.KeyGet, arg3 ...grpc.CallOption) (*krab.Response, error) {
	fake.hasPrivateKeyMutex.Lock()
	ret, specificReturn := fake.hasPrivateKeyReturnsOnCall[len(fake.hasPrivateKeyArgsForCall)]
	fake.hasPrivateKeyArgsForCall = append(fake.hasPrivateKeyArgsForCall, struct {
		arg1 context.Context
		arg2 *krab.KeyGet
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	fake.recordInvocation("HasPrivateKey", []interface{}{arg1, arg2, arg3})
	fake.hasPrivateKeyMutex.Unlock()
	if fake.HasPrivateKeyStub != nil {
		return fake.HasPrivateKeyStub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.hasPrivateKeyReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceClient) HasPrivateKeyCallCount() int {
	fake.hasPrivateKeyMutex.RLock()
	defer fake.hasPrivateKeyMutex.RUnlock()
	return len(fake.hasPrivateKeyArgsForCall)
}

func (fake *FakeServiceClient) HasPrivateKeyCalls(stub func(context.Context, *krab.KeyGet, ...grpc.CallOption) (*krab.Response, error)) {
	fake.hasPrivateKeyMutex.Lock()
	defer fake.hasPrivateKeyMutex.Unlock()
	fake.HasPrivateKeyStub = stub
}

func (fake *FakeServiceClient) HasPrivateKeyArgsForCall(i int) (context.Context, *krab.KeyGet, []grpc.CallOption) {
	fake.hasPrivateKeyMutex.RLock()
	defer fake.hasPrivateKeyMutex.RUnlock()
	argsForCall := fake.hasPrivateKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeServiceClient) HasPrivateKeyReturns(result1 *krab.Response, result2 error) {
	fake.hasPrivateKeyMutex.Lock()
	defer fake.hasPrivateKeyMutex.Unlock()
	fake.HasPrivateKeyStub = nil
	fake.hasPrivateKeyReturns = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) HasPrivateKeyReturnsOnCall(i int, result1 *krab.Response, result2 error) {
	fake.hasPrivateKeyMutex.Lock()
	defer fake.hasPrivateKeyMutex.Unlock()
	fake.HasPrivateKeyStub = nil
	if fake.hasPrivateKeyReturnsOnCall == nil {
		fake.hasPrivateKeyReturnsOnCall = make(map[int]struct {
			result1 *krab.Response
			result2 error
		})
	}
	fake.hasPrivateKeyReturnsOnCall[i] = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) ListPrivateKeys(arg1 context.Context, arg2 *krab.KeyList, arg3 ...grpc.CallOption) (*krab.Response, error) {
	fake.listPrivateKeysMutex.Lock()
	ret, specificReturn := fake.listPrivateKeysReturnsOnCall[len(fake.listPrivateKeysArgsForCall)]
	fake.listPrivateKeysArgsForCall = append(fake.listPrivateKeysArgsForCall, struct {
		arg1 context.Context
		arg2 *krab.KeyList
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	fake.recordInvocation("ListPrivateKeys", []interface{}{arg1, arg2, arg3})
	fake.listPrivateKeysMutex.Unlock()
	if fake.ListPrivateKeysStub != nil {
		return fake.ListPrivateKeysStub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listPrivateKeysReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceClient) ListPrivateKeysCallCount() int {
	fake.listPrivateKeysMutex.RLock()
	defer fake.listPrivateKeysMutex.RUnlock()
	return len(fake.listPrivateKeysArgsForCall)
}

func (fake *FakeServiceClient) ListPrivateKeysCalls(stub func(context.Context, *krab.KeyList, ...grpc.CallOption) (*krab.Response, error)) {
	fake.listPrivateKeysMutex.Lock()
	defer fake.listPrivateKeysMutex.Unlock()
	fake.ListPrivateKeysStub = stub
}

func (fake *FakeServiceClient) ListPrivateKeysArgsForCall(i int) (context.Context, *krab.KeyList, []grpc.CallOption) {
	fake.listPrivateKeysMutex.RLock()
	defer fake.listPrivateKeysMutex.RUnlock()
	argsForCall := fake.listPrivateKeysArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeServiceClient) ListPrivateKeysReturns(result1 *krab.Response, result2 error) {
	fake.listPrivateKeysMutex.Lock()
	defer fake.listPrivateKeysMutex.Unlock()
	fake.ListPrivateKeysStub = nil
	fake.listPrivateKeysReturns = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) ListPrivateKeysReturnsOnCall(i int, result1 *krab.Response, result2 error) {
	fake.listPrivateKeysMutex.Lock()
	defer fake.listPrivateKeysMutex.Unlock()
	fake.ListPrivateKeysStub = nil
	if fake.listPrivateKeysReturnsOnCall == nil {
		fake.listPrivateKeysReturnsOnCall = make(map[int]struct {
			result1 *krab.Response
			result2 error
		})
	}
	fake.listPrivateKeysReturnsOnCall[i] = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) PutPrivateKey(arg1 context.Context, arg2 *krab.KeyPut, arg3 ...grpc.CallOption) (*krab.Response, error) {
	fake.putPrivateKeyMutex.Lock()
	ret, specificReturn := fake.putPrivateKeyReturnsOnCall[len(fake.putPrivateKeyArgsForCall)]
	fake.putPrivateKeyArgsForCall = append(fake.putPrivateKeyArgsForCall, struct {
		arg1 context.Context
		arg2 *krab.KeyPut
		arg3 []grpc.CallOption
	}{arg1, arg2, arg3})
	fake.recordInvocation("PutPrivateKey", []interface{}{arg1, arg2, arg3})
	fake.putPrivateKeyMutex.Unlock()
	if fake.PutPrivateKeyStub != nil {
		return fake.PutPrivateKeyStub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.putPrivateKeyReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceClient) PutPrivateKeyCallCount() int {
	fake.putPrivateKeyMutex.RLock()
	defer fake.putPrivateKeyMutex.RUnlock()
	return len(fake.putPrivateKeyArgsForCall)
}

func (fake *FakeServiceClient) PutPrivateKeyCalls(stub func(context.Context, *krab.KeyPut, ...grpc.CallOption) (*krab.Response, error)) {
	fake.putPrivateKeyMutex.Lock()
	defer fake.putPrivateKeyMutex.Unlock()
	fake.PutPrivateKeyStub = stub
}

func (fake *FakeServiceClient) PutPrivateKeyArgsForCall(i int) (context.Context, *krab.KeyPut, []grpc.CallOption) {
	fake.putPrivateKeyMutex.RLock()
	defer fake.putPrivateKeyMutex.RUnlock()
	argsForCall := fake.putPrivateKeyArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeServiceClient) PutPrivateKeyReturns(result1 *krab.Response, result2 error) {
	fake.putPrivateKeyMutex.Lock()
	defer fake.putPrivateKeyMutex.Unlock()
	fake.PutPrivateKeyStub = nil
	fake.putPrivateKeyReturns = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) PutPrivateKeyReturnsOnCall(i int, result1 *krab.Response, result2 error) {
	fake.putPrivateKeyMutex.Lock()
	defer fake.putPrivateKeyMutex.Unlock()
	fake.PutPrivateKeyStub = nil
	if fake.putPrivateKeyReturnsOnCall == nil {
		fake.putPrivateKeyReturnsOnCall = make(map[int]struct {
			result1 *krab.Response
			result2 error
		})
	}
	fake.putPrivateKeyReturnsOnCall[i] = struct {
		result1 *krab.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deletePrivateKeyMutex.RLock()
	defer fake.deletePrivateKeyMutex.RUnlock()
	fake.getPrivateKeyMutex.RLock()
	defer fake.getPrivateKeyMutex.RUnlock()
	fake.hasPrivateKeyMutex.RLock()
	defer fake.hasPrivateKeyMutex.RUnlock()
	fake.listPrivateKeysMutex.RLock()
	defer fake.listPrivateKeysMutex.RUnlock()
	fake.putPrivateKeyMutex.RLock()
	defer fake.putPrivateKeyMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ krab.ServiceClient = new(FakeServiceClient)
